name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Android SDK tools
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window

      - name: Install dependencies
        run: yarn install    # أو npm ci

      - name: Prebuild Expo (if using Expo)
        run: npx expo prebuild --platform android

      # 执行 gradlew داخل android/
      - name: Grant execute permission to gradlew
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
