name: Android CI

on:
  workflow_dispatch:             # يتيح التشغيل اليدوي
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK tools
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window

      - name: Install dependencies
        run: npm ci            # أو yarn install

      - name: Prebuild Expo (if using Expo Managed)
        run: npx expo prebuild --platform android

      - name: Grant execute permission to gradlew
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
